name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy: # https://github.com/actions/deploy-pages
    name: GitHub Pages deployment
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Remove some files
        run: |
          rm LICENSE

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
